"""empty message

Revision ID: 971da8bf49cd
Revises: 
Create Date: 2019-11-27 20:53:29.088365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '971da8bf49cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('title', sa.String(length=50), nullable=True))
    op.drop_index('name', table_name='article')
    op.create_unique_constraint(None, 'article', ['title'])
    op.drop_column('article', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'article', type_='unique')
    op.create_index('name', 'article', ['name'], unique=True)
    op.drop_column('article', 'title')
    op.drop_column('article', 'timestamp')
    op.drop_column('article', 'content')
    # ### end Alembic commands ###
