"""empty message

Revision ID: a3742d196482
Revises: 580954f26379
Create Date: 2020-02-02 19:43:34.791030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3742d196482'
down_revision = '580954f26379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('奖项',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('awardname', sa.Text(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('我',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('经历',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyname', sa.String(length=30), nullable=True),
    sa.Column('begintime', sa.Date(), nullable=True),
    sa.Column('endtime', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('companyname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('经历')
    op.drop_table('我')
    op.drop_table('奖项')
    # ### end Alembic commands ###
