"""empty message

Revision ID: c5310ac63418
Revises: a3742d196482
Create Date: 2020-02-02 19:45:34.028916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5310ac63418'
down_revision = 'a3742d196482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('awardname', sa.Text(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyname', sa.String(length=30), nullable=True),
    sa.Column('begintime', sa.Date(), nullable=True),
    sa.Column('endtime', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('companyname')
    )
    op.create_table('me',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('奖项')
    op.drop_index('companyname', table_name='经历')
    op.drop_table('经历')
    op.drop_index('name', table_name='我')
    op.drop_table('我')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('我',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', '我', ['name'], unique=True)
    op.create_table('经历',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('companyname', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('begintime', sa.DATE(), nullable=True),
    sa.Column('endtime', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('companyname', '经历', ['companyname'], unique=True)
    op.create_table('奖项',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('awardname', mysql.TEXT(), nullable=True),
    sa.Column('time', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('me')
    op.drop_table('experience')
    op.drop_table('award')
    # ### end Alembic commands ###
